import type { Metadata } from "next";
import { Roboto } from "next/font/google";
// 공통 컴포넌트
import SideNavigation from "@/components/common/navigation/SideNavigation";
// 전역 CSS
import "@/styles/globals.css";

const roboto = Roboto({
    subsets: ["latin"],
    weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
    title: "TO DO BOARD",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={roboto.className}>
                <SideNavigation />
                {children}
            </body>
        </html>
    );
}
